version: "3.5"
services:
    springapp:
      container_name: libreria
      volumes:
        - ./build/libs/:/app
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/libreria
      depends_on:
        - db
      build:
        context: ./
        target: api
      ports:
        - 8085:8085
    db:
      container_name: libreria_db
      volumes:
        - ./tables:/docker-entrypoint-initdb.d/
      build:
        context: ./
        target: postgres
      environment:
        - POSTGRES_USER=fernando
        - POSTGRES_PASSWORD=disashop
        - POSTGRES_DB=libreria
        - PGDATA=/var/lib/postgresql/data/pgdata
      ports:
        - 5432:5432
      restart: always
