version: "3.5"
services:
    springapp:
      container_name: libreria
      build:
        context: ./
        target: dev
      volumes:
      - ./Compilacion:/build/libs
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/libreria
      ports:
        - 8085:8085
      depends_on:
        - db
    db:
      container_name: libreria_db
      build:
        context: ./
        target: base
      volumes:
        - ./tables:/docker-entrypoint-initdb.d/
      environment:
        - POSTGRES_USER=fernando
        - POSTGRES_PASSWORD=disashop
        - POSTGRES_DB=libreria
        - PGDATA=/var/lib/postgresql/data/pgdata
      ports:
        - 5432:5432
      restart: always
