version: "3.5"
services:
    springapp:
      container_name: libreria
      build:
        context: ./Compilacion
        target: api
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/libreria
      volumes:
        - ./build/libs/:/project/
      ports:
        - 8085:8085
      depends_on:
        - db
    db:
      container_name: libreria_db
      volumes:
        - ./tables:/docker-entrypoint-initdb.d/
      build:
        context: ./Compilacion
        target: postgres
      environment:
        - POSTGRES_USER=fernando
        - POSTGRES_PASSWORD=disashop
        - POSTGRES_DB=libreria
        - PGDATA=/var/lib/postgresql/data/pgdata
      ports:
        - 5432:5432
      restart: always
